version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: assinaturas-db
    restart: always
    environment:
      POSTGRES_DB: Assinaturas
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "5440:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
    driver: local
