version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: assinaturas-db
    restart: always
    environment:
      POSTGRES_DB: Assinaturas
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "5440:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.4
    container_name: keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/Assinaturas
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: secret
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      ports:
        -"8081:8080"
      depends_on:
        -postgres

volumes:
  pg_data:
    driver: local
