name: Java CI with Maven and Docker

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read
  packages: read
  security-events: write

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  TAG: 0.1.0


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Debug Docker
        run: docker --version && docker info

      - name: Debug - Listar Variáveis de Ambiente
        run: env

      - name: Build Docker image
        run: docker build -t $DOCKER_USERNAME/gerenciador-de-assinaturas:$TAG .

      - name: Login to Docker Hub
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Push Docker image
        run: docker push $DOCKER_USERNAME/gerenciador-de-assinaturas:$TAG
