name: Java CI with Maven and Docker

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read
  packages: read
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Debug Docker
        run: docker --version && docker info

      - name: Debug - Listar Variáveis de Ambiente
        run: env

      - name: Verify Credentials
        run: |
          echo "Username: ${{ secrets.DOCKER_USERNAME }}"
          if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then
            echo "Erro: DOCKER_USERNAME está vazio!"
            exit 1
          fi
          if [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then
            echo "Erro: DOCKER_PASSWORD está vazio!"
            exit 1
          fi
        shell: bash

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/gerenciador-de-assinaturas:latest .

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/gerenciador-de-assinaturas:latest
